# -*- coding: utf-8 -*-
"""Week 5 (b)-Deploy Your Model as a Live Web App.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rYwN4fZZtJ-251YumqTMiZ7A3r7wC_G9
"""

#Import LIbraries
import pandas as pd
import joblib
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

#LOad dataset
df = pd.read_csv('/content/creditcard.csv')

df.head(5)

#Preprocess
scaler = StandardScaler()
df['scaled_amount'] = scaler.fit_transform(df[['Amount']])

# Select top relevant PCA features + scaled amount for simple app inputs
selected_features = ['V1', 'V2', 'V3', 'V4', 'V10', 'scaled_amount']
X = df[selected_features]
y = df['Class']

#Train Test Split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

#Train Model with Class Weighting
model = LogisticRegression(class_weight='balanced', random_state=42)
model.fit(X_train, y_train)

#Save Model and Scaler
joblib.dump(model, 'fraud_model.pkl')
joblib.dump(scaler, 'scaler.pkl')

print("Model and Scaler successfully saved to disk as 'fraud_model.pkl' and 'scaler.pkl'.")